repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-yaml
  - id: trailing-whitespace
    exclude: .*(\.md|\.ttl)$

- repo: https://github.com/ambv/black
  rev: 21.7b0
  hooks:
  - id: black

- repo: https://github.com/pycqa/pylint
  rev: 'v2.10.1'
  hooks:
  - id: pylint
    args:
      - --rcfile
      - dic2owl/setup.cfg
      - --disable
      - import-error
